### ISSUE TITLE
escaping quotes in nested strings 

### ISSUE THREAD

**Issue by lerljaku** [nreco/lambdaparser#23]
### parsing fails with string in expression

test string:

```
var exp = "true ? \"<br><br><span style=\\\"color:red;\\\">hello</span> world\" : \"\""
            
var result = SUT.Eval(exp, new Dictionary<string, object>());
```

fails with

```
NReco.Linq.LambdaParserException : Expected ':' at 30: true ? "<br><br><span style=\"color:red;\">hello</span> world" : ""
   at NReco.Linq.LambdaParser.ParseConditional(String expr, Int32 start)
   at NReco.Linq.LambdaParser.Parse(String expr)
   at NReco.Linq.LambdaParser.Eval(String expr, Func`2 getVarValue)
   at NReco.Linq.LambdaParser.Eval(String expr, IDictionary`2 vars)
```

**Comment by VitaliyMF** [comment]
`\"` is not a valid escape sequence for LambdaParser, only way to include " is `""` (sequence of 2 double quotes that are treated as ").

If you want to support \" you can simply do `exp.Replace("\\\"", "\"\"") `

**Comment by lerljaku** [comment]
ty!, its all cool for me :]
